### ISSUE TITLE
hi，我在使用之后没法图片可以缓存下来，但是没法在下载完成实时展示

### ISSUE THREAD

**Issue by poos** [CivelXu/Kingfisher-Texture#1]
如下
` lazy var leftImageNode = ASNetworkImageNode.imageNode()`
`leftImageNode.url = ....`

当我刷新时候可以从存储中加载，但是首次加载回调已经完成，图片却没有更新
你有碰到这个问题吗，谢谢

**Comment by CivelXu** [comment]
@poos 不太理解 你说的 首次加载回调已经完成，图片却没有更新 是个什么问题
我在项目中的使用是没有问题的; 如果有缓存的话 是只加载缓存的  不再进行网络请求

**Comment by poos** [comment]
感谢回复，我仔细对照了下：
用你写的没有问题
`callbackQueue.async(execute: { completion(image, error, nil, url) })`
而我这样写的
`callbackQueue.async(execute: { completion(image, error, operation, url) })`
所以下载回调之后图片没有实时更新，很奇怪。
查阅了接口文档
`/**
 @param image The image that was downloaded, if the image could be successfully downloaded; nil otherwise.
 @param error An error describing why the download of `URL` failed, if the download failed; nil otherwise.
 @param downloadIdentifier The identifier for the download task that completed.
 @param userInfo Any additional info that your downloader would like to communicate through Texture.
 */`
又看到Texture文档ASBasicImageDownloader.mm是如下写的
`
    if (completionBlock) {
      dispatch_async(callbackQueue, ^{
        completionBlock(image, error, nil, nil);
      });
    }`
用起来没问题，就先这样吧

**Comment by CivelXu** [comment]
@poos 第三个参数 是 downloadIdentifier The identifier for the download task that completed.
operation 是要返回出去的
